In [5]:
import json

from Eval import eval_answer

In [6]:
data_experiment=eval_answer()
data_60_examples=eval_answer(flag=True)

questions_records[k] dict_keys(['original', 'v2'])
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'Qwen/Qwen2.5-7B-Instruct:together'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'meta-llama/Llama-4-Scout-17B-16E-Instruct:groq'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'meta-llama/Llama-3.3-70B-Instruct:groq'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2-Exp:novita'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2:novita'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'hf', 'model': 'Qwen/Qwen3-235B-A22B-Instruct-2507:novita'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'qwen3-32b'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'qwen3-30b-a3b-thinking-2507'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'qwen3-coder-30b-a3b-instruct'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'mistral-large-instruct'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'deepseek-r1'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name experiment
selected_model {'agent': 'gwdg', 'model': 'deepseek-r1-distill-llama-70b'}
Show_train_set False
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges no
Crossed_edges no
Crossed_edges no
Crossed_edges True
Crossed_edges True
Crossed_edges True
questions_records[k] dict_keys(['original', 'v2'])
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'meta-llama/Llama-4-Scout-17B-16E-Instruct:groq'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2-Exp:novita'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2:novita'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'Qwen/Qwen3-235B-A22B-Instruct-2507:novita'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'gwdg', 'model': 'qwen3-32b'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'gwdg', 'model': 'qwen3-30b-a3b-thinking-2507'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'gwdg', 'model': 'qwen3-coder-30b-a3b-instruct'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'gwdg', 'model': 'mistral-large-instruct'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'gwdg', 'model': 'deepseek-r1'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2-Exp:novita'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
##############################
data_name 60
selected_model {'agent': 'hf', 'model': 'deepseek-ai/DeepSeek-V3.2:novita'}
Show_train_set False
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True
Crossed_edges True

In [7]:
import pandas as pd
Data_experiment = pd.DataFrame(data_experiment)
Data_experiment.head()

,correctness,duration,type_,Crossed_edges,no_of_edges,no_of_nodes,model
0,1,1.124367,DI,no,3,4,Qwen/Qwen2.5-7B-Instruct:together
1,0,0.881759,mixed,no,3,4,Qwen/Qwen2.5-7B-Instruct:together
2,0,1.291369,inDI,no,3,4,Qwen/Qwen2.5-7B-Instruct:together
3,0,0.894541,DI,True,3,4,Qwen/Qwen2.5-7B-Instruct:together
4,0,1.762372,mixed,True,3,4,Qwen/Qwen2.5-7B-Instruct:together

In [8]:
overall = Data_experiment.groupby('model')['correctness'].mean().reset_index()   
overall.head()

                                       model  correctness
0          Qwen/Qwen2.5-7B-Instruct:together     0.055556
1  Qwen/Qwen3-235B-A22B-Instruct-2507:novita     0.111111
2       deepseek-ai/DeepSeek-V3.2-Exp:novita     0.166667
3           deepseek-ai/DeepSeek-V3.2:novita     0.111111
4                                deepseek-r1     0.055556

In [11]:
overall = Data_experiment.groupby(['model','type_'])['correctness'].mean().reset_index()   
overall.head()

                                       model  type_  correctness
0          Qwen/Qwen2.5-7B-Instruct:together     DI     0.166667
1          Qwen/Qwen2.5-7B-Instruct:together   inDI     0.000000
2          Qwen/Qwen2.5-7B-Instruct:together  mixed     0.000000
3  Qwen/Qwen3-235B-A22B-Instruct-2507:novita     DI     0.333333
4  Qwen/Qwen3-235B-A22B-Instruct-2507:novita   inDI     0.000000

In [ ]:
overall = Data_experiment.groupby(['model','Crossed_edges'])['correctness'].mean().reset_index()   
overall.head()

import plotly.express as px
template='ggplot2'
df = overall
fig = px.bar(df, x="model", y="correctness",
             color='Crossed_edges', barmode='group',template=template,text_auto=True,
             height=300)
fig.show()
fig.write_image("images/duration_di_indi.png")

In [ ]:
import pandas as pd
Data_60 = pd.DataFrame(data_60_examples)
Data_60.head()

In [ ]:
overall = Data_60.groupby(['model','no_of_edges'])['correctness'].mean().reset_index()   
overall.head()

import plotly.express as px
template='ggplot2'
df = overall
fig = px.bar(df, x="model", y="correctness",
             color='no_of_edges', barmode='group',template=template,text_auto=True,
             height=500)
fig.show()
fig.write_image("images/duration_di_indi.png")